/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'title' : IDL.Text,
  'author' : IDL.Text,
  'totalPages' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'initializeBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'title' : IDL.Text,
    'author' : IDL.Text,
    'totalPages' : IDL.Nat,
  });
  
  return IDL.Service({
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'initializeBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };